### ISSUE TITLE
VOX, RTL und RTL II Addons funktionieren nicht mehr

### ISSUE THREAD

**Issue by RomanOnymous** [bromix/repository.bromix#1]
Hi,
Die Streams in den Addons von VOX, RTL und RTL II funktionieren nicht mehr, stattdessen kommt eine Error-Meldung

**Comment by bromix** [comment]
Bitte in den entsprechenden Addons schauen, das hier ist nur das Repos...und bitte auf 2.1.2 updaten, ist schon seit gestern behoben.
https://github.com/bromix/plugin.video.rtl-now.de/issues/8
